### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by tedcasey** [tg44/custom-gatling-proto-sample#2]
Can you add a license to show whether or not this code is useable in derivative works?  It's a great example and I'd like to use it in a project, but won't be able to unless there is some sort of open source license like Apache 2.  If you'd like I can open a PR from my fork that would add a license to the project.

**Comment by tg44** [comment]
Ofc you can use this! I added a readme (that points to the blogpost I wrote), and a license.

**Comment by tedcasey** [comment]
Awesome!  Thank you!
